/* Generated by scripts/gen-workspace.py. Composes the Workspace v19 screens in template order. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import type { Vals } from "../vals";
import { ShellBotincLanding } from "./shell-botinc-landing";
import { ShellPlansAndCredits } from "./shell-plans-and-credits";
import { ShellSidebar } from "./shell-sidebar";
import { ShellCloseNavigation } from "./shell-close-navigation";
import { ShellMobileTabs9 } from "./shell-mobile-tabs9";
import { AppTopbar } from "./app-topbar";
import { PageConversation } from "./page-conversation";
import { PageConversations } from "./page-conversations";
import { PageWorkConversation } from "./page-work-conversation";
import { PageSchedule } from "./page-schedule";
import { PageAutopilotDetails } from "./page-autopilot-details";
import { PageWork } from "./page-work";
import { PageIssueDetail } from "./page-issue-detail";
import { PagePlugins } from "./page-plugins";
import { PageModelAccounts } from "./page-model-accounts";
import { PageAutopilotConversation } from "./page-autopilot-conversation";
import { PageProfile } from "./page-profile";
import { PageSkillsAndPreferences } from "./page-skills-and-preferences";
import { PageSettingsHomeV7 } from "./page-settings-home-v7";
import { PageSettings } from "./page-settings";
import { BodyInput } from "./body-input";
import { BodyInput1 } from "./body-input-1";
import { PageAskOperator } from "./page-ask-operator";
import { PagePfTip16 } from "./page-pf-tip16";
import { PageC9Card16 } from "./page-c9-card16";
import { PageCallWithYourOperator } from "./page-call-with-your-operator";
import { PageAskOperatorAboutThisPage } from "./page-ask-operator-about-this-page";
import { PageConversationInspector } from "./page-conversation-inspector";
import { PageWorkDetails } from "./page-work-details";
import { OverlayOverlay12 } from "./overlay-overlay12";
import { OverlayOverlay121 } from "./overlay-overlay12-1";
import { ShellToast } from "./shell-toast";
import { ShellDismissMenu } from "./shell-dismiss-menu";
import { ShellDismissPicker } from "./shell-dismiss-picker";
import { ShellFileInput11 } from "./shell-file-input11";
import { ShellImagePreview } from "./shell-image-preview";
import { ShellOverlay12 } from "./shell-overlay12";
import { ShellAccountScrim13 } from "./shell-account-scrim13";
import { DialogSkilldetaildialog } from "./dialog-skilldetaildialog";
import { DialogSkillcreatedialog } from "./dialog-skillcreatedialog";
import { DialogCheckoutdialog } from "./dialog-checkoutdialog";
import { DialogIssueeditdialog } from "./dialog-issueeditdialog";
import { DialogComputerdialogv6 } from "./dialog-computerdialogv6";
import { DialogRepodialogv6 } from "./dialog-repodialogv6";
import { DialogWorkflowdialogv6 } from "./dialog-workflowdialogv6";
import { DialogSourcesdialog } from "./dialog-sourcesdialog";
import { DialogConnectdialog } from "./dialog-connectdialog";
import { DialogImporteddialog } from "./dialog-importeddialog";
import { DialogAgentdialog } from "./dialog-agentdialog";
import { DialogModeldialog } from "./dialog-modeldialog";
import { DialogAgentconfigdialog } from "./dialog-agentconfigdialog";
import { DialogAutomationdialog } from "./dialog-automationdialog";
import { DialogPlansdialog } from "./dialog-plansdialog";
import { DialogTopupdialog } from "./dialog-topupdialog";
import { DialogFileviewdialog16 } from "./dialog-fileviewdialog16";
import { DialogRepopickdialog16 } from "./dialog-repopickdialog16";
import { DialogNewworkspacedialog16 } from "./dialog-newworkspacedialog16";
import { DialogAuthdialog } from "./dialog-authdialog";
import { DialogSearchdialog } from "./dialog-searchdialog";
import { DialogImportdialog14 } from "./dialog-importdialog14";
import { DialogInvitedialog14 } from "./dialog-invitedialog14";
import { DialogRoledialog14 } from "./dialog-roledialog14";
import { DialogForkdialog14 } from "./dialog-forkdialog14";
import { DialogNewissuedialog } from "./dialog-newissuedialog";
import { DialogAddaccountdialog } from "./dialog-addaccountdialog";
import { DialogAccountdialog } from "./dialog-accountdialog";
import { DialogFundingdialog8 } from "./dialog-fundingdialog8";
import { DialogCancelissuedialog } from "./dialog-cancelissuedialog";
import { DialogCalldecisiondialog9 } from "./dialog-calldecisiondialog9";
import { DialogTaskdetailsdialog9 } from "./dialog-taskdetailsdialog9";
import { DialogVoicestartdialog10 } from "./dialog-voicestartdialog10";
import { DialogPlugindialog10 } from "./dialog-plugindialog10";
import { DialogMcpdialog10 } from "./dialog-mcpdialog10";
import { DialogRepairdialog10 } from "./dialog-repairdialog10";
import { DialogAutopilotform10 } from "./dialog-autopilotform10";
import { DialogQuickaccountdialog10 } from "./dialog-quickaccountdialog10";
import { DialogFundingsettingsdialog10 } from "./dialog-fundingsettingsdialog10";
import { DialogGenericdialog } from "./dialog-genericdialog";
import { DialogTopupdialog19 } from "./dialog-topupdialog19";
import { DialogPreviewdialog } from "./dialog-previewdialog";
import { DialogTwostepdialog19 } from "./dialog-twostepdialog19";
import { DialogDevicesdialog19 } from "./dialog-devicesdialog19";
import { DialogKeysdialog19 } from "./dialog-keysdialog19";
import { DialogHaserror } from "./dialog-haserror";

export function WorkspaceView({ v }: { v: Vals }) {
  return (
    <div className={v.rootClass} data-theme={v.theme}>
      <ShellBotincLanding v={v} />
      <ShellPlansAndCredits v={v} />
      <ShellSidebar v={v} />
      <ShellCloseNavigation v={v} />
      <ShellMobileTabs9 v={v} />
      <div className="app-main">
        <AppTopbar v={v} />
        <div className={`workspace-body ${v.panelOpenClass}`}>
          <PageConversation v={v} />
          <PageConversations v={v} />
          <PageWorkConversation v={v} />
          <PageSchedule v={v} />
          <PageAutopilotDetails v={v} />
          <PageWork v={v} />
          <PageIssueDetail v={v} />
          <PagePlugins v={v} />
          <PageModelAccounts v={v} />
          <PageAutopilotConversation v={v} />
          <PageProfile v={v} />
          <PageSkillsAndPreferences v={v} />
          <PageSettingsHomeV7 v={v} />
          <PageSettings v={v} />
          <BodyInput v={v} />
          <BodyInput v={v} />
          <PageAskOperator v={v} />
          <PagePfTip16 v={v} />
          <PageC9Card16 v={v} />
          <PageCallWithYourOperator v={v} />
          <PageAskOperatorAboutThisPage v={v} />
          <PageConversationInspector v={v} />
          <PageWorkDetails v={v} />
        </div>
        <OverlayOverlay12 v={v} />
        <OverlayOverlay12 v={v} />
      </div>
      <ShellToast v={v} />
      <ShellDismissMenu v={v} />
      <ShellDismissPicker v={v} />
      <ShellFileInput11 v={v} />
      <ShellImagePreview v={v} />
      <ShellOverlay12 v={v} />
      <ShellAccountScrim13 v={v} />
      {v.dialogOpen ? (
        <div className="modal-shade" onClick={v.backdropClick}>
          <section className={v.modalClass} role="dialog" aria-modal="true" aria-labelledby="dialog-title">
            <button className="modal-close icon-button" aria-label="Close dialog" onClick={v.closeDialog}>
              <svg
                className="ui-icon "
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.75"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <use href="/i15.svg#x" />
              </svg>
            </button>
            <DialogSkilldetaildialog v={v} />
            <DialogSkillcreatedialog v={v} />
            <DialogCheckoutdialog v={v} />
            <DialogIssueeditdialog v={v} />
            <DialogComputerdialogv6 v={v} />
            <DialogRepodialogv6 v={v} />
            <DialogWorkflowdialogv6 v={v} />
            <DialogSourcesdialog v={v} />
            <DialogConnectdialog v={v} />
            <DialogImporteddialog v={v} />
            <DialogAgentdialog v={v} />
            <DialogModeldialog v={v} />
            <DialogAgentconfigdialog v={v} />
            <DialogAutomationdialog v={v} />
            <DialogPlansdialog v={v} />
            <DialogTopupdialog v={v} />
            <DialogFileviewdialog16 v={v} />
            <DialogRepopickdialog16 v={v} />
            <DialogNewworkspacedialog16 v={v} />
            <DialogAuthdialog v={v} />
            <DialogSearchdialog v={v} />
            <DialogImportdialog14 v={v} />
            <DialogInvitedialog14 v={v} />
            <DialogRoledialog14 v={v} />
            <DialogForkdialog14 v={v} />
            <DialogNewissuedialog v={v} />
            <DialogAddaccountdialog v={v} />
            <DialogAccountdialog v={v} />
            <DialogFundingdialog8 v={v} />
            <DialogCancelissuedialog v={v} />
            <DialogCalldecisiondialog9 v={v} />
            <DialogTaskdetailsdialog9 v={v} />
            <DialogVoicestartdialog10 v={v} />
            <DialogPlugindialog10 v={v} />
            <DialogMcpdialog10 v={v} />
            <DialogRepairdialog10 v={v} />
            <DialogAutopilotform10 v={v} />
            <DialogQuickaccountdialog10 v={v} />
            <DialogFundingsettingsdialog10 v={v} />
            <DialogGenericdialog v={v} />
            <DialogTopupdialog19 v={v} />
            <DialogPreviewdialog v={v} />
            <DialogTwostepdialog19 v={v} />
            <DialogDevicesdialog19 v={v} />
            <DialogKeysdialog19 v={v} />
            <DialogHaserror v={v} />
          </section>
        </div>
      ) : null}
    </div>
  );
}
